/* Auto-generated by cbindgen. Do not edit. */

#ifndef AEROBLEND_FFI_H
#define AEROBLEND_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * 기총 프리셋 ID
 */
typedef enum GunPresetC {
    /**
     * .50 cal M2 Browning (12.7mm)
     */
    BrowningM2 = 0,
    /**
     * 20mm AN/M2 cannon
     */
    AnM2Cannon = 1,
    /**
     * 7.7mm Vickers
     */
    Vickers77 = 2,
} GunPresetC;

/**
 * Opaque loaded model handle.
 */
typedef struct LoadedModel LoadedModel;

/**
 * Opaque physics engine handle.
 */
typedef struct PhysicsEngine PhysicsEngine;

/**
 * 무장 시스템 불투명 핸들 (C++에서는 포인터로만 사용)
 */
typedef struct WeaponSystemHandle WeaponSystemHandle;

/**
 * 3D vector (f64) - FFI safe.
 */
typedef struct Vec3C {
    double x;
    double y;
    double z;
} Vec3C;

/**
 * Aircraft model data.
 */
typedef struct AircraftModelC {
    uint32_t mesh_count;
    double mass_kg;
    struct Vec3C bbox_min;
    struct Vec3C bbox_max;
} AircraftModelC;

/**
 * Single mesh data for GPU upload.
 */
typedef struct MeshDataC {
    const float (*vertices)[3];
    const float (*normals)[3];
    const float (*uvs)[2];
    const uint32_t *indices;
    uint32_t vertex_count;
    uint32_t index_count;
    const char *name;
} MeshDataC;

/**
 * 3x3 matrix (f64, column-major) - FFI safe.
 */
typedef struct Mat3C {
    double m[9];
} Mat3C;

/**
 * Pre-computed flight characteristics - FFI safe POD.
 *
 * These parameters characterize an aircraft's flight envelope and are used
 * by the mouse-aim instructor to adapt control gains per airframe.
 */
typedef struct FlightCharacteristicsC {
    /**
     * Stall speed at sea level (m/s)
     */
    double stall_speed_ms;
    /**
     * Reference cruise speed (m/s): ~1.3 * stall speed
     */
    double ref_speed_ms;
    /**
     * Maximum angle of attack before stall (rad)
     */
    double max_aoa_rad;
    /**
     * Total wing area (m^2)
     */
    double total_wing_area_m2;
    /**
     * Control authority: control moment / inertia ratio (average)
     */
    double control_authority;
    /**
     * Per-axis control authority: pitch torque / Ixx
     */
    double ca_pitch;
    /**
     * Per-axis control authority: roll torque / Izz
     */
    double ca_roll;
    /**
     * Per-axis control authority: yaw torque / Iyy
     */
    double ca_yaw;
    /**
     * Wing loading (kg/m^2)
     */
    double wing_loading_kg_m2;
    /**
     * Thrust-to-weight ratio
     */
    double thrust_to_weight;
    /**
     * Maximum pitch rate from elevator authority (rad/s)
     */
    double max_pitch_rate_rad_s;
    /**
     * Maximum roll rate from aileron authority (rad/s)
     */
    double max_roll_rate_rad_s;
} FlightCharacteristicsC;

/**
 * Aircraft physics state - FFI safe POD.
 */
typedef struct AircraftPhysicsStateC {
    struct Vec3C position;
    struct Vec3C velocity;
    struct Vec3C acceleration;
    struct Mat3C orientation;
    struct Vec3C angular_velocity;
    double mass_kg;
    double airspeed_ms;
    double angle_of_attack_rad;
    double sideslip_rad;
    double altitude_m;
    double mach;
    double heading_rad;
    double pitch_rad;
    double roll_rad;
    double g_force;
    double climb_rate_ms;
    double ground_speed_ms;
    double throttle;
    struct FlightCharacteristicsC flight_chars;
} AircraftPhysicsStateC;

/**
 * Control input state - FFI safe.
 */
typedef struct ControlStateC {
    double pitch;
    double yaw;
    double roll;
    double throttle;
    double brake;
    double flaps;
    uint8_t gear_down;
    uint8_t airbrake;
    uint8_t firing;
    struct Vec3C mouse_aim_direction;
} ControlStateC;

/**
 * Camera state - FFI safe.
 */
typedef struct CameraStateC {
    struct Vec3C position;
    struct Vec3C target;
    struct Vec3C up;
    double fov_deg;
    double near;
    double far;
    uint32_t mode;
} CameraStateC;

/**
 * 4x4 matrix (f32, column-major for OpenGL) - FFI safe.
 */
typedef struct Mat4C {
    float m[16];
} Mat4C;

/**
 * 무장 시스템 요약 상태 (Rust → C++)
 */
typedef struct WeaponStateC {
    uint32_t gun_count;
    uint32_t total_ammo_remaining;
    uint32_t total_ammo_capacity;
    uint8_t is_firing;
    enum GunPresetC gun_preset;
} WeaponStateC;

/**
 * 탄환 렌더링 상태 (Rust → C++)
 */
typedef struct ProjectileStateC {
    struct Vec3C position;
    struct Vec3C velocity;
    uint8_t active;
} ProjectileStateC;

/**
 * Quaternion (f64) - FFI safe.
 */
typedef struct QuatC {
    double w;
    double x;
    double y;
    double z;
} QuatC;

/**
 * 기총 스펙 (C 호환)
 */
typedef struct GunSpecC {
    double caliber_mm;
    double mass_kg;
    double muzzle_velocity_ms;
    double drag_coefficient;
    double cross_section_m2;
    double fire_rate_rpm;
    struct Vec3C muzzle_position;
    struct Vec3C muzzle_direction;
    uint32_t ammo_capacity;
    double spread_rad;
} GunSpecC;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new physics engine instance.
 *
 * # Returns
 * Non-null pointer to a `PhysicsEngine` that must be freed with `aeroblend_physics_destroy`.
 */
struct PhysicsEngine *aeroblend_physics_create(void);

/**
 * Destroy a physics engine instance and free its memory.
 *
 * # Safety
 * `engine` must be either null or a valid pointer returned by `aeroblend_physics_create`.
 * Must not be called more than once with the same pointer.
 */
void aeroblend_physics_destroy(struct PhysicsEngine *engine);

/**
 * Load an aircraft model from a glTF/glb file.
 *
 * # Safety
 * `path` must be either null or a valid pointer to a null-terminated C string.
 *
 * # Returns
 * Non-null pointer on success, null on failure. Must be freed with `aeroblend_model_destroy`.
 */
struct LoadedModel *aeroblend_model_load(const char *path);

/**
 * Destroy a loaded model and free its memory.
 *
 * # Safety
 * `model` must be either null or a valid pointer returned by `aeroblend_model_load`.
 * Must not be called more than once with the same pointer.
 */
void aeroblend_model_destroy(struct LoadedModel *model);

/**
 * Get aircraft model metadata (mesh count, mass, bounding box).
 *
 * # Safety
 * `model` must be either null or a valid pointer to a `LoadedModel`.
 */
struct AircraftModelC aeroblend_model_get_data(const struct LoadedModel *model);

/**
 * Get mesh data at the given index.
 *
 * # Safety
 * `model` must be either null or a valid pointer to a `LoadedModel`.
 * Returned pointers are only valid as long as the `LoadedModel` exists.
 */
struct MeshDataC aeroblend_model_get_mesh(const struct LoadedModel *model, uint32_t index);

/**
 * Initialize physics engine with an aircraft model.
 *
 * # Safety
 * `engine` and `model` must be either null or valid pointers.
 * `engine` must not be accessed concurrently during this call.
 */
struct AircraftPhysicsStateC aeroblend_physics_init(struct PhysicsEngine *engine,
                                                    const struct LoadedModel *model);

/**
 * Initialize physics engine with default flying state (no model needed).
 *
 * Sets up the engine at 500m altitude, 80 m/s forward velocity, 50% throttle
 * with default aerodynamic surfaces and engines.
 *
 * # Safety
 * `engine` must be either null or a valid pointer to a `PhysicsEngine`.
 * `engine` must not be accessed concurrently during this call.
 */
struct AircraftPhysicsStateC aeroblend_physics_init_default(struct PhysicsEngine *engine);

/**
 * Initialize physics engine with a built-in aircraft profile.
 *
 * Profile IDs: 0 = biplane (default), 1 = monoplane (Cessna 172), 2 = jet (F-16).
 *
 * # Safety
 * `engine` must be either null or a valid pointer to a `PhysicsEngine`.
 * `engine` must not be accessed concurrently during this call.
 */
struct AircraftPhysicsStateC aeroblend_physics_init_profile(struct PhysicsEngine *engine,
                                                            uint32_t profile_id);

/**
 * Step the physics simulation forward by `dt` seconds.
 *
 * # Safety
 * `engine` and `controls` must be either null or valid pointers.
 * `engine` must not be accessed concurrently during this call.
 */
struct AircraftPhysicsStateC aeroblend_physics_step(struct PhysicsEngine *engine,
                                                    const struct ControlStateC *controls,
                                                    double dt);

/**
 * Get pre-computed flight characteristics for the current aircraft.
 *
 * # Safety
 * `engine` must be either null or a valid pointer to a `PhysicsEngine`.
 */
struct FlightCharacteristicsC aeroblend_physics_get_flight_chars(const struct PhysicsEngine *engine);

/**
 * Update chase camera position following the aircraft.
 *
 * # Safety
 * `state` and `current_cam` must be either null or valid pointers.
 */
struct CameraStateC aeroblend_camera_update_chase(const struct AircraftPhysicsStateC *state,
                                                  const struct CameraStateC *current_cam,
                                                  double dt);

/**
 * Update cockpit camera position inside the aircraft.
 *
 * # Safety
 * `state` must be either null or a valid pointer.
 */
struct CameraStateC aeroblend_camera_update_cockpit(const struct AircraftPhysicsStateC *state);

/**
 * Build OpenGL view matrix from camera state.
 *
 * # Safety
 * `camera` must be either null or a valid pointer.
 */
struct Mat4C aeroblend_build_view_matrix(const struct CameraStateC *camera);

/**
 * Build OpenGL perspective projection matrix.
 *
 * # Safety
 * `camera` must be either null or a valid pointer.
 */
struct Mat4C aeroblend_build_projection_matrix(const struct CameraStateC *camera, double aspect);

/**
 * Build OpenGL model matrix from orientation and position.
 *
 * # Safety
 * `orientation` and `position` must be either null or valid pointers.
 */
struct Mat4C aeroblend_build_model_matrix(const struct Mat3C *orientation,
                                          const struct Vec3C *position);

/**
 * 무장 시스템 생성 — 프리셋별 기본 기총 2정 (좌우 대칭).
 *
 * # Returns
 * 반드시 `aeroblend_weapons_destroy`로 해제해야 하는 핸들 포인터.
 */
struct WeaponSystemHandle *aeroblend_weapons_create(enum GunPresetC preset);

/**
 * 무장 시스템 해제.
 *
 * # Safety
 * `weapons`는 null이거나 `aeroblend_weapons_create`가 반환한 유효한 포인터여야 한다.
 * 동일 포인터로 두 번 이상 호출하면 안 된다.
 */
void aeroblend_weapons_destroy(struct WeaponSystemHandle *weapons);

/**
 * 무장 시스템 업데이트 — 매 물리 프레임 호출 (120Hz).
 *
 * 항공기 상태에서 위치/자세/속도를 추출하고, firing 플래그에 따라
 * 기총 발사 및 탄환 물리를 한 스텝 진행한다.
 *
 * # Safety
 * `weapons`와 `aircraft_state`는 null이거나 유효한 포인터여야 한다.
 */
struct WeaponStateC aeroblend_weapons_update(struct WeaponSystemHandle *weapons,
                                             const struct AircraftPhysicsStateC *aircraft_state,
                                             uint8_t firing,
                                             double dt);

/**
 * 활성 탄환 목록 복사 — 렌더링용.
 *
 * `out_buffer`에 최대 `buffer_size`개의 활성 탄환 상태를 기록하고,
 * 실제 기록된 수를 반환한다.
 *
 * # Safety
 * `weapons`는 null이거나 유효한 포인터여야 한다.
 * `out_buffer`는 최소 `buffer_size` 크기의 배열을 가리켜야 한다.
 */
uint32_t aeroblend_weapons_get_projectiles(const struct WeaponSystemHandle *weapons,
                                           struct ProjectileStateC *out_buffer,
                                           uint32_t buffer_size);

/**
 * 전체 재장전 — 모든 기총의 잔탄을 최대치로 복원.
 *
 * # Safety
 * `weapons`는 null이거나 유효한 포인터여야 한다.
 */
void aeroblend_weapons_reload(struct WeaponSystemHandle *weapons);

/**
 * 잔탄수 조회 — 전체 기총의 합산 잔탄수를 반환.
 *
 * # Safety
 * `weapons`는 null이거나 유효한 포인터여야 한다.
 */
uint32_t aeroblend_weapons_get_ammo(const struct WeaponSystemHandle *weapons);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AEROBLEND_FFI_H */
