@echo off
chcp 65001 >nul 2>&1
cd /d "%~dp0"

set "ADDON_SRC=%cd%\scripts\generate_example_aircraft.py"
set "PROJECT_ROOT=%cd%"

echo =========================================
echo   AeroBlend 딸깍 (Windows)
echo =========================================
echo.

:: ── 1. Blender 찾기 ──
set "BLENDER="

where blender >nul 2>&1
if %ERRORLEVEL% EQU 0 (
    set "BLENDER=blender"
    goto :found_blender
)

for /d %%D in ("C:\Program Files\Blender Foundation\Blender *") do (
    if exist "%%D\blender.exe" (
        set "BLENDER=%%D\blender.exe"
        goto :found_blender
    )
)

if exist "C:\Program Files (x86)\Steam\steamapps\common\Blender\blender.exe" (
    set "BLENDER=C:\Program Files (x86)\Steam\steamapps\common\Blender\blender.exe"
    goto :found_blender
)

echo [오류] Blender를 찾을 수 없습니다.
echo   https://blender.org 에서 설치하세요.
pause
exit /b 1

:found_blender
echo Blender: %BLENDER%

:: ── 2. Blender 버전 감지 ──
for /f "tokens=2 delims= " %%V in ('"%BLENDER%" --version 2^>nul ^| findstr /r "^Blender"') do (
    for /f "tokens=1,2 delims=." %%A in ("%%V") do (
        set "BLENDER_VER=%%A.%%B"
    )
)

echo Blender %BLENDER_VER% 감지

:: ── 3. 애드온 설치 (복사) ──
set "ADDONS_DIR=%APPDATA%\Blender Foundation\Blender\%BLENDER_VER%\scripts\addons"
if not exist "%ADDONS_DIR%" mkdir "%ADDONS_DIR%"

copy /Y "%ADDON_SRC%" "%ADDONS_DIR%\generate_example_aircraft.py" >nul
echo 애드온 설치 완료

:: ── 4. 자동 활성화 스타트업 스크립트 설치 ──
set "STARTUP_DIR=%APPDATA%\Blender Foundation\Blender\%BLENDER_VER%\scripts\startup"
if not exist "%STARTUP_DIR%" mkdir "%STARTUP_DIR%"

:: Python 경로에서 백슬래시를 이스케이프
set "PY_ROOT=%PROJECT_ROOT:\=/%"

(
echo """AeroBlend addon auto-enable (generated by DDALKAK)"""
echo import bpy
echo import addon_utils
echo.
echo def _enable_aeroblend^(^):
echo     addon_utils.enable^('generate_example_aircraft', default_set=True, persistent=True^)
echo     prefs = bpy.context.preferences.addons.get^('generate_example_aircraft'^)
echo     if prefs:
echo         prefs.preferences.project_root = r"%PY_ROOT%"
echo     bpy.ops.wm.save_userpref^(^)
echo     return None
echo.
echo bpy.app.timers.register^(_enable_aeroblend, first_interval=1.0^)
) > "%STARTUP_DIR%\aeroblend_autostart.py"

echo 자동 활성화 스크립트 설치 완료

:: ── 5. Blender 실행 ──
echo.
echo =========================================
echo   Blender 여는 중...
echo   사이드바(N) ^> AeroBlend 탭
echo =========================================

start "" "%BLENDER%"
